collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7956989
  lightness: 1
  brandStrength: 0.9040067
  rhythmicContrast: 0
typography_spectrum: 0.5573477
layout_spectrum: 0.4713262
name: GC
